name: "Terraform Apply"

on:
  push:
    branches: 
    - "issues/sjt/13-pipeline" 

  #schedule:
  #  - "30 7 * * 1,2,4,5"


jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.SANDBOX_AZ_CREDENTIALS }} 
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: 'terraform init'
      working-directory: './azure/01-hub-spoke-test'
      run: |
        export AZ_CREDENTIALS=<<<EOF
        ${{ secrets.SANDBOX_AZ_CREDENTIALS }}
        EOF
        export ARM_CLIENT_ID=$(echo $AZ_CREDENTIALS | jq '.clientId')
        echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID}"

        export ARM_CLIENT_SECRET=$(echo $AZ_CREDENTIALS | jq '.clientSecret')
        export ARM_TENANT_ID=$(echo $AZ_CREDENTIALS | jq '.tenantId')
        export ARM_SUBSCRIPTION_ID=$(echo $AZ_CREDENTIALS | jq '.subscriptionId')
        terraform init

    - name: 'terraform apply'
      working-directory: './azure/01-hub-spoke-test'
      run: |
        terraform apply -auto-approve