name: Generate terraform docs
on:
  - pull_request

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ./azure/03-core-infrastructure
        output-file: ./docs/terraform-docs.md
        output-method: replace
        git-push: "true"
        template: |
            ---
            title: Terraform Documents
            parent: Azure
            grand_parent: Terraform
            layout: page
            ---
            
            {{ .Content }}