name: Generate terraform docs
on:
  - pull_request

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        find-dir: ./
        output-file: ./docs.md
        output-method: replace
        output-format: markdown table
        git-push: "true"
        template: |
            ---
            title: {{ .Module.XMLName }}
            parent: Azure
            layout: page
            grand_parent: Terraform
            has_children: true
            ---
            
            {{ .Content }}